// Kynth Core node description for n8n.
//
// AUTO-GENERATED by apps/parserail/scripts/generate-clients.ts — do NOT edit by hand.
// Regenerate with `pnpm gen:clients` in apps/parserail after changing the catalog.

import type { INodeTypeDescription, NodeConnectionType } from 'n8n-workflow';

export const kynthNodeDescription = {
	...({
	"displayName": "Kynth Core",
	"name": "kynthCore",
	"icon": "file:kynth.svg",
	"group": [
		"transform"
	],
	"version": 1,
	"subtitle": "={{ $parameter[\"operation\"] }}",
	"description": "39 finished-job AI endpoints — documents to schema-valid JSON, extraction, triage, research, moderation, and agent memory. Task-named pricing; failed calls never burn credits.",
	"defaults": {
		"name": "Kynth Core"
	},
	"usableAsTool": true,
	"credentials": [
		{
			"name": "kynthApi",
			"required": true
		}
	],
	"requestDefaults": {
		"baseURL": "https://api.kynth.studio",
		"headers": {
			"Content-Type": "application/json"
		}
	},
	"properties": [
		{
			"displayName": "Operation",
			"name": "operation",
			"type": "options",
			"noDataExpression": true,
			"default": "parse",
			"options": [
				{
					"name": "Document Parse",
					"value": "parse",
					"action": "Document Parse",
					"description": "Any invoice, receipt, EOB, ERA, or COI — PDF or image — into structured, validated JSON.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/parse"
						}
					}
				},
				{
					"name": "Field Extraction",
					"value": "extract",
					"action": "Field Extraction",
					"description": "Pull a field set you define out of any block of text. You name the fields; you get typed values with confidence.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/extract"
						}
					}
				},
				{
					"name": "Classification",
					"value": "classify",
					"action": "Classification",
					"description": "Route or tag text against your own taxonomy — a label, a confidence, and a one-line rationale.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/classify"
						}
					}
				},
				{
					"name": "Summarize",
					"value": "summarize",
					"action": "Summarize",
					"description": "A meeting transcript, thread, or report → a tight summary, key points, and extracted action items.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/summarize"
						}
					}
				},
				{
					"name": "PII Redaction",
					"value": "redact",
					"action": "PII Redaction",
					"description": "Detect and strip names, emails, phones, SSNs, cards, and PHI from text before you store or log it.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/redact"
						}
					}
				},
				{
					"name": "Sentiment",
					"value": "sentiment",
					"action": "Sentiment",
					"description": "Turn a review or support message into a sentiment score, per-aspect breakdown, and the themes driving it.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/sentiment"
						}
					}
				},
				{
					"name": "Contract Analysis",
					"value": "contract",
					"action": "Contract Analysis",
					"description": "A contract → parties, effective date, term, renewal, governing law, obligations, and flagged risk clauses.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/contract"
						}
					}
				},
				{
					"name": "Chargeback Representment",
					"value": "chargeback",
					"action": "Chargeback Representment",
					"description": "Dispute details → a representment narrative, an evidence checklist, the right reason code, and a win-likelihood.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/chargeback"
						}
					}
				},
				{
					"name": "Company Enrichment",
					"value": "enrich",
					"action": "Company Enrichment",
					"description": "A domain or work email → a structured company profile: name, description, industry, HQ, size, and links.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/enrich"
						}
					}
				},
				{
					"name": "Invoice Extraction",
					"value": "invoice",
					"action": "Invoice Extraction",
					"description": "An invoice — PDF, photo, or text — into vendor, dates, PO refs, tax, totals, and clean line items.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/invoice"
						}
					}
				},
				{
					"name": "Receipt Extraction",
					"value": "receipt",
					"action": "Receipt Extraction",
					"description": "A receipt into merchant, items, totals, payment method, and an expense category — built for expense flows.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/receipt"
						}
					}
				},
				{
					"name": "Statement Parsing",
					"value": "statement",
					"action": "Statement Parsing",
					"description": "A bank or card statement into the account, the period, balances, and every transaction as a normalized row.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/statement"
						}
					}
				},
				{
					"name": "Resume Parsing",
					"value": "resume",
					"action": "Resume Parsing",
					"description": "A resume or CV into a structured candidate profile: contact, skills, experience, education, and links.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/resume"
						}
					}
				},
				{
					"name": "Table Extraction",
					"value": "tables",
					"action": "Table Extraction",
					"description": "Every table in a document — even scanned — as clean headers and rows, ready for your spreadsheet or DB.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/tables"
						}
					}
				},
				{
					"name": "Document Splitting",
					"value": "split",
					"action": "Document Splitting",
					"description": "A multi-document scan bundle classified and split: what each document is, where it starts and ends, and a summary.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/split"
						}
					}
				},
				{
					"name": "Document Comparison",
					"value": "compare",
					"action": "Document Comparison",
					"description": "Two versions of a contract or document → every material change, what it means, and the risk it carries.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/compare"
						}
					}
				},
				{
					"name": "Structure to Your Schema",
					"value": "structure",
					"action": "Structure to Your Schema",
					"description": "Any messy input — text, HTML, an email — plus YOUR JSON schema → output shaped to it, validated against your required fields and property types, with an automatic corrective retry and a `valid` flag.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/structure"
						}
					}
				},
				{
					"name": "Record Normalization",
					"value": "normalize",
					"action": "Record Normalization",
					"description": "A batch of messy records → clean canonical rows, with a change log of every fix (casing, formats, dedup-ready values).",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/normalize"
						}
					}
				},
				{
					"name": "Entity Matching",
					"value": "match",
					"action": "Entity Matching",
					"description": "Two record sets → which rows are the same real-world thing, with confidence and reasoning. Fuzzy names, typos, aliases handled.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/match"
						}
					}
				},
				{
					"name": "Batch Categorization",
					"value": "categorize",
					"action": "Batch Categorization",
					"description": "Up to a hundred items against your taxonomy in one call — products, transactions, tickets — each with a confidence.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/categorize"
						}
					}
				},
				{
					"name": "Collections Sequence",
					"value": "dunning",
					"action": "Collections Sequence",
					"description": "An overdue invoice → a ready-to-send collection sequence, escalating at the right pace and tone for how late it is.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/dunning"
						}
					}
				},
				{
					"name": "3-Way Match",
					"value": "po-match",
					"action": "3-Way Match",
					"description": "Invoice vs purchase order vs receipt → matched, partial, or mismatched, with every discrepancy flagged and sized.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/po-match"
						}
					}
				},
				{
					"name": "Quote Builder",
					"value": "quote",
					"action": "Quote Builder",
					"description": "A job description plus your rates → an itemized, professional quote with assumptions and scope notes spelled out.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/quote"
						}
					}
				},
				{
					"name": "Fraud Triage",
					"value": "fraud-flag",
					"action": "Fraud Triage",
					"description": "An order or transaction in context → a risk score, the signals driving it, and the checks worth running before you ship.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/fraud-flag"
						}
					}
				},
				{
					"name": "Reply Drafting",
					"value": "reply",
					"action": "Reply Drafting",
					"description": "A customer thread plus your context → a ready-to-send reply in the right tone, with an internal note for the agent.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/reply"
						}
					}
				},
				{
					"name": "Ticket Triage",
					"value": "triage",
					"action": "Ticket Triage",
					"description": "A support ticket → priority, category, the team it belongs to, sentiment, SLA risk, and a suggested first response.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/triage"
						}
					}
				},
				{
					"name": "Meeting Minutes",
					"value": "minutes",
					"action": "Meeting Minutes",
					"description": "A meeting transcript → clean minutes: summary, decisions made, action items with owners, and open questions.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/minutes"
						}
					}
				},
				{
					"name": "Outreach Sequence",
					"value": "outreach",
					"action": "Outreach Sequence",
					"description": "An enriched lead plus what you sell → a personalized outreach sequence that references what actually makes them a fit.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/outreach"
						}
					}
				},
				{
					"name": "Review Response",
					"value": "review-reply",
					"action": "Review Response",
					"description": "A customer review → a brand-safe public response, the issues to log, and whether it needs human escalation.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/review-reply"
						}
					}
				},
				{
					"name": "Content Moderation",
					"value": "moderate",
					"action": "Content Moderation",
					"description": "Text or an image against YOUR policy → allow, review, or block, with the categories and excerpts that drove the call.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/moderate"
						}
					}
				},
				{
					"name": "Brand-Voice Rewrite",
					"value": "rewrite",
					"action": "Brand-Voice Rewrite",
					"description": "Any copy → your brand voice. Describe the voice or paste a sample; get the rewrite and what changed.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/rewrite"
						}
					}
				},
				{
					"name": "Product Copy",
					"value": "product-copy",
					"action": "Product Copy",
					"description": "Specs and an audience → listing-ready titles, bullets, a description, and SEO keywords — per channel.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/product-copy"
						}
					}
				},
				{
					"name": "Image Description",
					"value": "describe",
					"action": "Image Description",
					"description": "An image → accessible alt text, a caption, tags, and any text found inside it. Accessibility and catalogs in one call.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/describe"
						}
					}
				},
				{
					"name": "Research Brief",
					"value": "research",
					"action": "Research Brief",
					"description": "A company or topic → a multi-source, citation-backed brief: what it is, what changed lately, and what matters. Real web work.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/research"
						}
					}
				},
				{
					"name": "Lead Screening",
					"value": "screen",
					"action": "Lead Screening",
					"description": "A lead plus your ICP criteria → a web-grounded qualification verdict with the evidence for and against.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/screen"
						}
					}
				},
				{
					"name": "Transcription",
					"value": "transcribe",
					"action": "Transcription",
					"description": "An audio recording → accurate text with speakers and paragraph timestamps. Meetings, calls, voice notes.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/transcribe"
						}
					}
				},
				{
					"name": "Agent Memory",
					"value": "memory",
					"action": "Agent Memory",
					"description": "Store, search, and forget memories for your agents — semantic recall on your own namespace, no vector DB to run.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/memory"
						}
					}
				},
				{
					"name": "Image Generation",
					"value": "image",
					"action": "Image Generation",
					"description": "A prompt → a production-ready image. Marketing visuals, product scenes, and consistent brand imagery.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/image"
						}
					}
				},
				{
					"name": "Text to Speech",
					"value": "speak",
					"action": "Text to Speech",
					"description": "Text → natural speech audio, ready to embed. Voice notes, IVR lines, narration.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "/v1/speak"
						}
					}
				}
			]
		},
		{
			"displayName": "File URL",
			"name": "parse_fileUrl",
			"type": "string",
			"default": "",
			"description": "Public URL to a PDF or image. Provide this or Text.",
			"displayOptions": {
				"show": {
					"operation": [
						"parse"
					]
				}
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "fileUrl",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Text",
			"name": "parse_text",
			"type": "string",
			"typeOptions": {
				"rows": 4
			},
			"default": "",
			"description": "Raw text, if you already have it. Provide this or File URL.",
			"displayOptions": {
				"show": {
					"operation": [
						"parse"
					]
				}
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "text",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Doc Type",
			"name": "parse_docType",
			"description": "Optional hint, e.g. \"invoice\".",
			"displayOptions": {
				"show": {
					"operation": [
						"parse"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "docType",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Text",
			"name": "extract_text",
			"displayOptions": {
				"show": {
					"operation": [
						"extract"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"typeOptions": {
				"rows": 4
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "text"
				}
			}
		},
		{
			"displayName": "Fields (comma-separated)",
			"name": "extract_fields",
			"description": "The field names to pull out.",
			"displayOptions": {
				"show": {
					"operation": [
						"extract"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "fields",
					"value": "={{ $value.split(\",\").map(s => s.trim()).filter(Boolean) }}"
				}
			}
		},
		{
			"displayName": "Instructions",
			"name": "extract_instructions",
			"description": "Optional extra guidance.",
			"displayOptions": {
				"show": {
					"operation": [
						"extract"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "instructions",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Text",
			"name": "classify_text",
			"displayOptions": {
				"show": {
					"operation": [
						"classify"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"typeOptions": {
				"rows": 4
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "text"
				}
			}
		},
		{
			"displayName": "Labels (comma-separated)",
			"name": "classify_labels",
			"displayOptions": {
				"show": {
					"operation": [
						"classify"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "labels",
					"value": "={{ $value.split(\",\").map(s => s.trim()).filter(Boolean) }}"
				}
			}
		},
		{
			"displayName": "Multi",
			"name": "classify_multi",
			"description": "Allow multiple labels.",
			"displayOptions": {
				"show": {
					"operation": [
						"classify"
					]
				}
			},
			"type": "boolean",
			"default": false,
			"routing": {
				"send": {
					"type": "body",
					"property": "multi"
				}
			}
		},
		{
			"displayName": "Instructions",
			"name": "classify_instructions",
			"displayOptions": {
				"show": {
					"operation": [
						"classify"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "instructions",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Text",
			"name": "summarize_text",
			"displayOptions": {
				"show": {
					"operation": [
						"summarize"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"typeOptions": {
				"rows": 4
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "text"
				}
			}
		},
		{
			"displayName": "Length",
			"name": "summarize_length",
			"displayOptions": {
				"show": {
					"operation": [
						"summarize"
					]
				}
			},
			"type": "options",
			"options": [
				{
					"name": "Brief",
					"value": "brief"
				},
				{
					"name": "Standard",
					"value": "standard"
				},
				{
					"name": "Detailed",
					"value": "detailed"
				}
			],
			"default": "standard",
			"routing": {
				"send": {
					"type": "body",
					"property": "length"
				}
			}
		},
		{
			"displayName": "Action Items",
			"name": "summarize_actionItems",
			"displayOptions": {
				"show": {
					"operation": [
						"summarize"
					]
				}
			},
			"type": "boolean",
			"default": true,
			"routing": {
				"send": {
					"type": "body",
					"property": "actionItems"
				}
			}
		},
		{
			"displayName": "Text",
			"name": "redact_text",
			"displayOptions": {
				"show": {
					"operation": [
						"redact"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"typeOptions": {
				"rows": 4
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "text"
				}
			}
		},
		{
			"displayName": "Types (comma-separated)",
			"name": "redact_types",
			"description": "Entity types to redact; omit for all.",
			"displayOptions": {
				"show": {
					"operation": [
						"redact"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "types",
					"value": "={{ $value.split(\",\").map(s => s.trim()).filter(Boolean) }}"
				}
			}
		},
		{
			"displayName": "Placeholder",
			"name": "redact_placeholder",
			"displayOptions": {
				"show": {
					"operation": [
						"redact"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "placeholder",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Text",
			"name": "sentiment_text",
			"displayOptions": {
				"show": {
					"operation": [
						"sentiment"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"typeOptions": {
				"rows": 4
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "text"
				}
			}
		},
		{
			"displayName": "Aspects (comma-separated)",
			"name": "sentiment_aspects",
			"description": "Optional aspects to break out.",
			"displayOptions": {
				"show": {
					"operation": [
						"sentiment"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "aspects",
					"value": "={{ $value.split(\",\").map(s => s.trim()).filter(Boolean) }}"
				}
			}
		},
		{
			"displayName": "File URL",
			"name": "contract_fileUrl",
			"type": "string",
			"default": "",
			"description": "Public URL to a PDF or image. Provide this or Text.",
			"displayOptions": {
				"show": {
					"operation": [
						"contract"
					]
				}
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "fileUrl",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Text",
			"name": "contract_text",
			"type": "string",
			"typeOptions": {
				"rows": 4
			},
			"default": "",
			"description": "Raw text, if you already have it. Provide this or File URL.",
			"displayOptions": {
				"show": {
					"operation": [
						"contract"
					]
				}
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "text",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Reason",
			"name": "chargeback_reason",
			"description": "The cardholder's dispute reason.",
			"displayOptions": {
				"show": {
					"operation": [
						"chargeback"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "reason"
				}
			}
		},
		{
			"displayName": "Transaction",
			"name": "chargeback_transaction",
			"displayOptions": {
				"show": {
					"operation": [
						"chargeback"
					]
				}
			},
			"required": true,
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"type": "body",
					"property": "transaction",
					"value": "={{ typeof $value === \"string\" ? JSON.parse($value) : $value }}"
				}
			}
		},
		{
			"displayName": "Evidence (comma-separated)",
			"name": "chargeback_evidence",
			"displayOptions": {
				"show": {
					"operation": [
						"chargeback"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "evidence",
					"value": "={{ $value.split(\",\").map(s => s.trim()).filter(Boolean) }}"
				}
			}
		},
		{
			"displayName": "Context",
			"name": "chargeback_context",
			"displayOptions": {
				"show": {
					"operation": [
						"chargeback"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "context",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Network",
			"name": "chargeback_network",
			"displayOptions": {
				"show": {
					"operation": [
						"chargeback"
					]
				}
			},
			"type": "options",
			"options": [
				{
					"name": "Visa",
					"value": "visa"
				},
				{
					"name": "Mastercard",
					"value": "mastercard"
				},
				{
					"name": "Amex",
					"value": "amex"
				},
				{
					"name": "Discover",
					"value": "discover"
				}
			],
			"default": "visa",
			"routing": {
				"send": {
					"type": "body",
					"property": "network"
				}
			}
		},
		{
			"displayName": "Domain",
			"name": "enrich_domain",
			"displayOptions": {
				"show": {
					"operation": [
						"enrich"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "domain",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Email",
			"name": "enrich_email",
			"displayOptions": {
				"show": {
					"operation": [
						"enrich"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "email",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "File URL",
			"name": "invoice_fileUrl",
			"type": "string",
			"default": "",
			"description": "Public URL to a PDF or image. Provide this or Text.",
			"displayOptions": {
				"show": {
					"operation": [
						"invoice"
					]
				}
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "fileUrl",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Text",
			"name": "invoice_text",
			"type": "string",
			"typeOptions": {
				"rows": 4
			},
			"default": "",
			"description": "Raw text, if you already have it. Provide this or File URL.",
			"displayOptions": {
				"show": {
					"operation": [
						"invoice"
					]
				}
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "text",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "File URL",
			"name": "receipt_fileUrl",
			"type": "string",
			"default": "",
			"description": "Public URL to a PDF or image. Provide this or Text.",
			"displayOptions": {
				"show": {
					"operation": [
						"receipt"
					]
				}
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "fileUrl",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Text",
			"name": "receipt_text",
			"type": "string",
			"typeOptions": {
				"rows": 4
			},
			"default": "",
			"description": "Raw text, if you already have it. Provide this or File URL.",
			"displayOptions": {
				"show": {
					"operation": [
						"receipt"
					]
				}
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "text",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "File URL",
			"name": "statement_fileUrl",
			"type": "string",
			"default": "",
			"description": "Public URL to a PDF or image. Provide this or Text.",
			"displayOptions": {
				"show": {
					"operation": [
						"statement"
					]
				}
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "fileUrl",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Text",
			"name": "statement_text",
			"type": "string",
			"typeOptions": {
				"rows": 4
			},
			"default": "",
			"description": "Raw text, if you already have it. Provide this or File URL.",
			"displayOptions": {
				"show": {
					"operation": [
						"statement"
					]
				}
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "text",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "File URL",
			"name": "resume_fileUrl",
			"type": "string",
			"default": "",
			"description": "Public URL to a PDF or image. Provide this or Text.",
			"displayOptions": {
				"show": {
					"operation": [
						"resume"
					]
				}
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "fileUrl",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Text",
			"name": "resume_text",
			"type": "string",
			"typeOptions": {
				"rows": 4
			},
			"default": "",
			"description": "Raw text, if you already have it. Provide this or File URL.",
			"displayOptions": {
				"show": {
					"operation": [
						"resume"
					]
				}
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "text",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "File URL",
			"name": "tables_fileUrl",
			"type": "string",
			"default": "",
			"description": "Public URL to a PDF or image. Provide this or Text.",
			"displayOptions": {
				"show": {
					"operation": [
						"tables"
					]
				}
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "fileUrl",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Text",
			"name": "tables_text",
			"type": "string",
			"typeOptions": {
				"rows": 4
			},
			"default": "",
			"description": "Raw text, if you already have it. Provide this or File URL.",
			"displayOptions": {
				"show": {
					"operation": [
						"tables"
					]
				}
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "text",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "File URL",
			"name": "split_fileUrl",
			"type": "string",
			"default": "",
			"description": "Public URL to a PDF or image. Provide this or Text.",
			"displayOptions": {
				"show": {
					"operation": [
						"split"
					]
				}
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "fileUrl",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Text",
			"name": "split_text",
			"type": "string",
			"typeOptions": {
				"rows": 4
			},
			"default": "",
			"description": "Raw text, if you already have it. Provide this or File URL.",
			"displayOptions": {
				"show": {
					"operation": [
						"split"
					]
				}
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "text",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "A",
			"name": "compare_a",
			"description": "The earlier version (file, fileUrl, or text).",
			"displayOptions": {
				"show": {
					"operation": [
						"compare"
					]
				}
			},
			"required": true,
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"type": "body",
					"property": "a",
					"value": "={{ typeof $value === \"string\" ? JSON.parse($value) : $value }}"
				}
			}
		},
		{
			"displayName": "B",
			"name": "compare_b",
			"description": "The later version (file, fileUrl, or text).",
			"displayOptions": {
				"show": {
					"operation": [
						"compare"
					]
				}
			},
			"required": true,
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"type": "body",
					"property": "b",
					"value": "={{ typeof $value === \"string\" ? JSON.parse($value) : $value }}"
				}
			}
		},
		{
			"displayName": "Input",
			"name": "structure_input",
			"description": "Any messy input — text, HTML, an email, a JSON blob.",
			"displayOptions": {
				"show": {
					"operation": [
						"structure"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"typeOptions": {
				"rows": 4
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "input"
				}
			}
		},
		{
			"displayName": "Schema",
			"name": "structure_schema",
			"description": "The JSON Schema the output must conform to.",
			"displayOptions": {
				"show": {
					"operation": [
						"structure"
					]
				}
			},
			"required": true,
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"type": "body",
					"property": "schema",
					"value": "={{ typeof $value === \"string\" ? JSON.parse($value) : $value }}"
				}
			}
		},
		{
			"displayName": "Instructions",
			"name": "structure_instructions",
			"description": "Optional extra guidance.",
			"displayOptions": {
				"show": {
					"operation": [
						"structure"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "instructions",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Records",
			"name": "normalize_records",
			"description": "The messy records.",
			"displayOptions": {
				"show": {
					"operation": [
						"normalize"
					]
				}
			},
			"required": true,
			"type": "json",
			"default": "[]",
			"routing": {
				"send": {
					"type": "body",
					"property": "records",
					"value": "={{ typeof $value === \"string\" ? JSON.parse($value) : $value }}"
				}
			}
		},
		{
			"displayName": "Fields (comma-separated)",
			"name": "normalize_fields",
			"description": "Canonical field names to normalize into; omit to keep the input's fields.",
			"displayOptions": {
				"show": {
					"operation": [
						"normalize"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "fields",
					"value": "={{ $value.split(\",\").map(s => s.trim()).filter(Boolean) }}"
				}
			}
		},
		{
			"displayName": "Instructions",
			"name": "normalize_instructions",
			"description": "House rules, e.g. \"US phone format, uppercase state codes\".",
			"displayOptions": {
				"show": {
					"operation": [
						"normalize"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "instructions",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "A",
			"name": "match_a",
			"description": "First record set.",
			"displayOptions": {
				"show": {
					"operation": [
						"match"
					]
				}
			},
			"required": true,
			"type": "json",
			"default": "[]",
			"routing": {
				"send": {
					"type": "body",
					"property": "a",
					"value": "={{ typeof $value === \"string\" ? JSON.parse($value) : $value }}"
				}
			}
		},
		{
			"displayName": "B",
			"name": "match_b",
			"description": "Second record set.",
			"displayOptions": {
				"show": {
					"operation": [
						"match"
					]
				}
			},
			"required": true,
			"type": "json",
			"default": "[]",
			"routing": {
				"send": {
					"type": "body",
					"property": "b",
					"value": "={{ typeof $value === \"string\" ? JSON.parse($value) : $value }}"
				}
			}
		},
		{
			"displayName": "Keys (comma-separated)",
			"name": "match_keys",
			"description": "Fields that most identify an entity, e.g. [\"name\",\"email\"].",
			"displayOptions": {
				"show": {
					"operation": [
						"match"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "keys",
					"value": "={{ $value.split(\",\").map(s => s.trim()).filter(Boolean) }}"
				}
			}
		},
		{
			"displayName": "Items (comma-separated)",
			"name": "categorize_items",
			"description": "The things to categorize.",
			"displayOptions": {
				"show": {
					"operation": [
						"categorize"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "items",
					"value": "={{ $value.split(\",\").map(s => s.trim()).filter(Boolean) }}"
				}
			}
		},
		{
			"displayName": "Taxonomy (comma-separated)",
			"name": "categorize_taxonomy",
			"description": "Your categories.",
			"displayOptions": {
				"show": {
					"operation": [
						"categorize"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "taxonomy",
					"value": "={{ $value.split(\",\").map(s => s.trim()).filter(Boolean) }}"
				}
			}
		},
		{
			"displayName": "Multi",
			"name": "categorize_multi",
			"description": "Allow multiple categories per item.",
			"displayOptions": {
				"show": {
					"operation": [
						"categorize"
					]
				}
			},
			"type": "boolean",
			"default": false,
			"routing": {
				"send": {
					"type": "body",
					"property": "multi"
				}
			}
		},
		{
			"displayName": "Instructions",
			"name": "categorize_instructions",
			"displayOptions": {
				"show": {
					"operation": [
						"categorize"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "instructions",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Invoice",
			"name": "dunning_invoice",
			"displayOptions": {
				"show": {
					"operation": [
						"dunning"
					]
				}
			},
			"required": true,
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"type": "body",
					"property": "invoice",
					"value": "={{ typeof $value === \"string\" ? JSON.parse($value) : $value }}"
				}
			}
		},
		{
			"displayName": "Customer",
			"name": "dunning_customer",
			"displayOptions": {
				"show": {
					"operation": [
						"dunning"
					]
				}
			},
			"required": true,
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"type": "body",
					"property": "customer",
					"value": "={{ typeof $value === \"string\" ? JSON.parse($value) : $value }}"
				}
			}
		},
		{
			"displayName": "Tone",
			"name": "dunning_tone",
			"description": "Where to start the escalation.",
			"displayOptions": {
				"show": {
					"operation": [
						"dunning"
					]
				}
			},
			"type": "options",
			"options": [
				{
					"name": "Friendly",
					"value": "friendly"
				},
				{
					"name": "Firm",
					"value": "firm"
				},
				{
					"name": "Final",
					"value": "final"
				}
			],
			"default": "friendly",
			"routing": {
				"send": {
					"type": "body",
					"property": "tone"
				}
			}
		},
		{
			"displayName": "Channel",
			"name": "dunning_channel",
			"displayOptions": {
				"show": {
					"operation": [
						"dunning"
					]
				}
			},
			"type": "options",
			"options": [
				{
					"name": "Email",
					"value": "email"
				},
				{
					"name": "SMS",
					"value": "sms"
				}
			],
			"default": "email",
			"routing": {
				"send": {
					"type": "body",
					"property": "channel"
				}
			}
		},
		{
			"displayName": "Steps",
			"name": "dunning_steps",
			"displayOptions": {
				"show": {
					"operation": [
						"dunning"
					]
				}
			},
			"type": "number",
			"default": 3,
			"routing": {
				"send": {
					"type": "body",
					"property": "steps",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Invoice",
			"name": "poMatch_invoice",
			"description": "The invoice — structured JSON (e.g. /v1/invoice output) or raw text.",
			"displayOptions": {
				"show": {
					"operation": [
						"po-match"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "invoice"
				}
			}
		},
		{
			"displayName": "Purchase Order",
			"name": "poMatch_purchaseOrder",
			"description": "The PO — structured JSON or raw text.",
			"displayOptions": {
				"show": {
					"operation": [
						"po-match"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "purchaseOrder"
				}
			}
		},
		{
			"displayName": "Receipt",
			"name": "poMatch_receipt",
			"description": "Optional goods receipt / delivery note for a 3-way match.",
			"displayOptions": {
				"show": {
					"operation": [
						"po-match"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "receipt",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Tolerance Pct",
			"name": "poMatch_tolerancePct",
			"description": "Price variance tolerance in percent (default 2).",
			"displayOptions": {
				"show": {
					"operation": [
						"po-match"
					]
				}
			},
			"type": "number",
			"default": 0,
			"routing": {
				"send": {
					"type": "body",
					"property": "tolerancePct",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Job",
			"name": "quote_job",
			"description": "What the customer needs, in plain words.",
			"displayOptions": {
				"show": {
					"operation": [
						"quote"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "job"
				}
			}
		},
		{
			"displayName": "Rates",
			"name": "quote_rates",
			"description": "Your rate card / pricing rules, any format.",
			"displayOptions": {
				"show": {
					"operation": [
						"quote"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "rates",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Past Quotes",
			"name": "quote_pastQuotes",
			"description": "Optional examples of quotes you've sent.",
			"displayOptions": {
				"show": {
					"operation": [
						"quote"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "pastQuotes",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Currency",
			"name": "quote_currency",
			"displayOptions": {
				"show": {
					"operation": [
						"quote"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "currency",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Order",
			"name": "fraudFlag_order",
			"description": "The order/transaction: amount, email, addresses, IP, device, history — whatever you have.",
			"displayOptions": {
				"show": {
					"operation": [
						"fraud-flag"
					]
				}
			},
			"required": true,
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"type": "body",
					"property": "order",
					"value": "={{ typeof $value === \"string\" ? JSON.parse($value) : $value }}"
				}
			}
		},
		{
			"displayName": "Context",
			"name": "fraudFlag_context",
			"description": "Store context: typical order size, known patterns.",
			"displayOptions": {
				"show": {
					"operation": [
						"fraud-flag"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "context",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Thread",
			"name": "reply_thread",
			"description": "The email/ticket thread, newest last.",
			"displayOptions": {
				"show": {
					"operation": [
						"reply"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"typeOptions": {
				"rows": 4
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "thread"
				}
			}
		},
		{
			"displayName": "Context",
			"name": "reply_context",
			"description": "Policies, KB extracts, account facts the reply may use.",
			"displayOptions": {
				"show": {
					"operation": [
						"reply"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "context",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Tone",
			"name": "reply_tone",
			"displayOptions": {
				"show": {
					"operation": [
						"reply"
					]
				}
			},
			"type": "options",
			"options": [
				{
					"name": "Professional",
					"value": "professional"
				},
				{
					"name": "Friendly",
					"value": "friendly"
				},
				{
					"name": "Apologetic",
					"value": "apologetic"
				},
				{
					"name": "Firm",
					"value": "firm"
				}
			],
			"default": "professional",
			"routing": {
				"send": {
					"type": "body",
					"property": "tone"
				}
			}
		},
		{
			"displayName": "Goal",
			"name": "reply_goal",
			"description": "What the reply should achieve, e.g. \"offer refund, keep them\".",
			"displayOptions": {
				"show": {
					"operation": [
						"reply"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "goal",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Sender Name",
			"name": "reply_senderName",
			"description": "Sign-off name.",
			"displayOptions": {
				"show": {
					"operation": [
						"reply"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "senderName",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Ticket",
			"name": "triage_ticket",
			"description": "The ticket text (subject + body).",
			"displayOptions": {
				"show": {
					"operation": [
						"triage"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "ticket"
				}
			}
		},
		{
			"displayName": "Categories (comma-separated)",
			"name": "triage_categories",
			"description": "Your category set; omit for sensible defaults.",
			"displayOptions": {
				"show": {
					"operation": [
						"triage"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "categories",
					"value": "={{ $value.split(\",\").map(s => s.trim()).filter(Boolean) }}"
				}
			}
		},
		{
			"displayName": "Teams (comma-separated)",
			"name": "triage_teams",
			"description": "Routable teams.",
			"displayOptions": {
				"show": {
					"operation": [
						"triage"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "teams",
					"value": "={{ $value.split(\",\").map(s => s.trim()).filter(Boolean) }}"
				}
			}
		},
		{
			"displayName": "Transcript",
			"name": "minutes_transcript",
			"description": "The meeting transcript.",
			"displayOptions": {
				"show": {
					"operation": [
						"minutes"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"typeOptions": {
				"rows": 4
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "transcript"
				}
			}
		},
		{
			"displayName": "Attendees (comma-separated)",
			"name": "minutes_attendees",
			"displayOptions": {
				"show": {
					"operation": [
						"minutes"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "attendees",
					"value": "={{ $value.split(\",\").map(s => s.trim()).filter(Boolean) }}"
				}
			}
		},
		{
			"displayName": "Lead",
			"name": "outreach_lead",
			"description": "Who you're writing to — an enriched profile (e.g. /v1/enrich output) or notes.",
			"displayOptions": {
				"show": {
					"operation": [
						"outreach"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "lead"
				}
			}
		},
		{
			"displayName": "Product",
			"name": "outreach_product",
			"description": "What you sell and the value proposition.",
			"displayOptions": {
				"show": {
					"operation": [
						"outreach"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "product"
				}
			}
		},
		{
			"displayName": "Sender",
			"name": "outreach_sender",
			"displayOptions": {
				"show": {
					"operation": [
						"outreach"
					]
				}
			},
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"type": "body",
					"property": "sender",
					"value": "={{ typeof $value === \"string\" ? JSON.parse($value) : $value }}"
				}
			}
		},
		{
			"displayName": "Channel",
			"name": "outreach_channel",
			"displayOptions": {
				"show": {
					"operation": [
						"outreach"
					]
				}
			},
			"type": "options",
			"options": [
				{
					"name": "Email",
					"value": "email"
				},
				{
					"name": "Linkedin",
					"value": "linkedin"
				}
			],
			"default": "email",
			"routing": {
				"send": {
					"type": "body",
					"property": "channel"
				}
			}
		},
		{
			"displayName": "Steps",
			"name": "outreach_steps",
			"displayOptions": {
				"show": {
					"operation": [
						"outreach"
					]
				}
			},
			"type": "number",
			"default": 3,
			"routing": {
				"send": {
					"type": "body",
					"property": "steps",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Review",
			"name": "reviewReply_review",
			"description": "The customer review text.",
			"displayOptions": {
				"show": {
					"operation": [
						"review-reply"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "review"
				}
			}
		},
		{
			"displayName": "Rating",
			"name": "reviewReply_rating",
			"description": "Star rating if known.",
			"displayOptions": {
				"show": {
					"operation": [
						"review-reply"
					]
				}
			},
			"type": "number",
			"default": 0,
			"routing": {
				"send": {
					"type": "body",
					"property": "rating",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Business",
			"name": "reviewReply_business",
			"displayOptions": {
				"show": {
					"operation": [
						"review-reply"
					]
				}
			},
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"type": "body",
					"property": "business",
					"value": "={{ typeof $value === \"string\" ? JSON.parse($value) : $value }}"
				}
			}
		},
		{
			"displayName": "Resolution",
			"name": "reviewReply_resolution",
			"description": "What you can offer, e.g. \"replacement or refund\".",
			"displayOptions": {
				"show": {
					"operation": [
						"review-reply"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "resolution",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Text",
			"name": "moderate_text",
			"displayOptions": {
				"show": {
					"operation": [
						"moderate"
					]
				}
			},
			"type": "string",
			"default": "",
			"typeOptions": {
				"rows": 4
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "text",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Image",
			"name": "moderate_image",
			"displayOptions": {
				"show": {
					"operation": [
						"moderate"
					]
				}
			},
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"type": "body",
					"property": "image",
					"value": "={{ typeof $value === \"string\" ? JSON.parse($value) : $value }}"
				}
			}
		},
		{
			"displayName": "Image URL",
			"name": "moderate_imageUrl",
			"displayOptions": {
				"show": {
					"operation": [
						"moderate"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "imageUrl",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Policy",
			"name": "moderate_policy",
			"description": "YOUR rules, plain words — e.g. \"no medical claims, no competitor names\". Adds to the safety baseline.",
			"displayOptions": {
				"show": {
					"operation": [
						"moderate"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "policy",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Text",
			"name": "rewrite_text",
			"displayOptions": {
				"show": {
					"operation": [
						"rewrite"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"typeOptions": {
				"rows": 4
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "text"
				}
			}
		},
		{
			"displayName": "Voice",
			"name": "rewrite_voice",
			"description": "Describe the voice or paste a sample of it.",
			"displayOptions": {
				"show": {
					"operation": [
						"rewrite"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "voice",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Goal",
			"name": "rewrite_goal",
			"description": "E.g. \"tighter, more confident\".",
			"displayOptions": {
				"show": {
					"operation": [
						"rewrite"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "goal",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Audience",
			"name": "rewrite_audience",
			"displayOptions": {
				"show": {
					"operation": [
						"rewrite"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "audience",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Length",
			"name": "rewrite_length",
			"displayOptions": {
				"show": {
					"operation": [
						"rewrite"
					]
				}
			},
			"type": "options",
			"options": [
				{
					"name": "Shorter",
					"value": "shorter"
				},
				{
					"name": "Same",
					"value": "same"
				},
				{
					"name": "Longer",
					"value": "longer"
				}
			],
			"default": "same",
			"routing": {
				"send": {
					"type": "body",
					"property": "length"
				}
			}
		},
		{
			"displayName": "Product",
			"name": "productCopy_product",
			"displayOptions": {
				"show": {
					"operation": [
						"product-copy"
					]
				}
			},
			"required": true,
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"type": "body",
					"property": "product",
					"value": "={{ typeof $value === \"string\" ? JSON.parse($value) : $value }}"
				}
			}
		},
		{
			"displayName": "Channel",
			"name": "productCopy_channel",
			"displayOptions": {
				"show": {
					"operation": [
						"product-copy"
					]
				}
			},
			"type": "options",
			"options": [
				{
					"name": "Amazon",
					"value": "amazon"
				},
				{
					"name": "Shopify",
					"value": "shopify"
				},
				{
					"name": "Generic",
					"value": "generic"
				}
			],
			"default": "generic",
			"routing": {
				"send": {
					"type": "body",
					"property": "channel"
				}
			}
		},
		{
			"displayName": "Image",
			"name": "describe_image",
			"displayOptions": {
				"show": {
					"operation": [
						"describe"
					]
				}
			},
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"type": "body",
					"property": "image",
					"value": "={{ typeof $value === \"string\" ? JSON.parse($value) : $value }}"
				}
			}
		},
		{
			"displayName": "Image URL",
			"name": "describe_imageUrl",
			"displayOptions": {
				"show": {
					"operation": [
						"describe"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "imageUrl",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Purpose",
			"name": "describe_purpose",
			"displayOptions": {
				"show": {
					"operation": [
						"describe"
					]
				}
			},
			"type": "options",
			"options": [
				{
					"name": "Alt",
					"value": "alt"
				},
				{
					"name": "Caption",
					"value": "caption"
				},
				{
					"name": "Product",
					"value": "product"
				},
				{
					"name": "Detailed",
					"value": "detailed"
				}
			],
			"default": "alt",
			"routing": {
				"send": {
					"type": "body",
					"property": "purpose"
				}
			}
		},
		{
			"displayName": "Query",
			"name": "research_query",
			"description": "The company, topic, or question to research.",
			"displayOptions": {
				"show": {
					"operation": [
						"research"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "query"
				}
			}
		},
		{
			"displayName": "Focus",
			"name": "research_focus",
			"description": "What matters to you, e.g. \"pricing changes and funding\".",
			"displayOptions": {
				"show": {
					"operation": [
						"research"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "focus",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Depth",
			"name": "research_depth",
			"description": "Deep reads more sources.",
			"displayOptions": {
				"show": {
					"operation": [
						"research"
					]
				}
			},
			"type": "options",
			"options": [
				{
					"name": "Standard",
					"value": "standard"
				},
				{
					"name": "Deep",
					"value": "deep"
				}
			],
			"default": "standard",
			"routing": {
				"send": {
					"type": "body",
					"property": "depth"
				}
			}
		},
		{
			"displayName": "Lead",
			"name": "screen_lead",
			"description": "Company domain, name, or a pasted profile.",
			"displayOptions": {
				"show": {
					"operation": [
						"screen"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "lead"
				}
			}
		},
		{
			"displayName": "Criteria",
			"name": "screen_criteria",
			"description": "Your ICP, plain words — e.g. \"B2B SaaS, 20-200 employees, US, sells to finance teams\".",
			"displayOptions": {
				"show": {
					"operation": [
						"screen"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "criteria"
				}
			}
		},
		{
			"displayName": "Audio",
			"name": "transcribe_audio",
			"displayOptions": {
				"show": {
					"operation": [
						"transcribe"
					]
				}
			},
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"type": "body",
					"property": "audio",
					"value": "={{ typeof $value === \"string\" ? JSON.parse($value) : $value }}"
				}
			}
		},
		{
			"displayName": "Audio URL",
			"name": "transcribe_audioUrl",
			"displayOptions": {
				"show": {
					"operation": [
						"transcribe"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "audioUrl",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Diarize",
			"name": "transcribe_diarize",
			"description": "Label speakers.",
			"displayOptions": {
				"show": {
					"operation": [
						"transcribe"
					]
				}
			},
			"type": "boolean",
			"default": true,
			"routing": {
				"send": {
					"type": "body",
					"property": "diarize"
				}
			}
		},
		{
			"displayName": "Language",
			"name": "transcribe_language",
			"description": "BCP-47 hint, e.g. \"en\".",
			"displayOptions": {
				"show": {
					"operation": [
						"transcribe"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "language",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Op",
			"name": "memory_op",
			"description": "The operation.",
			"displayOptions": {
				"show": {
					"operation": [
						"memory"
					]
				}
			},
			"required": true,
			"type": "options",
			"options": [
				{
					"name": "Store",
					"value": "store"
				},
				{
					"name": "Search",
					"value": "search"
				},
				{
					"name": "Forget",
					"value": "forget"
				}
			],
			"default": "store",
			"routing": {
				"send": {
					"type": "body",
					"property": "op"
				}
			}
		},
		{
			"displayName": "Namespace",
			"name": "memory_namespace",
			"description": "Your partition key — an agent ID, a user ID. Defaults to \"default\".",
			"displayOptions": {
				"show": {
					"operation": [
						"memory"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "namespace",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Content",
			"name": "memory_content",
			"description": "Store: the memory text.",
			"displayOptions": {
				"show": {
					"operation": [
						"memory"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "content",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Metadata",
			"name": "memory_metadata",
			"description": "Store: attached metadata, returned on recall.",
			"displayOptions": {
				"show": {
					"operation": [
						"memory"
					]
				}
			},
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"type": "body",
					"property": "metadata",
					"value": "={{ typeof $value === \"string\" ? JSON.parse($value) : $value }}"
				}
			}
		},
		{
			"displayName": "Query",
			"name": "memory_query",
			"description": "Search: what to recall.",
			"displayOptions": {
				"show": {
					"operation": [
						"memory"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "query",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Limit",
			"name": "memory_limit",
			"description": "Search: max results.",
			"displayOptions": {
				"show": {
					"operation": [
						"memory"
					]
				}
			},
			"type": "number",
			"default": 5,
			"routing": {
				"send": {
					"type": "body",
					"property": "limit",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "ID",
			"name": "memory_id",
			"description": "Forget: the memory ID (or omit with namespace to wipe it).",
			"displayOptions": {
				"show": {
					"operation": [
						"memory"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "id",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Prompt",
			"name": "image_prompt",
			"description": "What to generate.",
			"displayOptions": {
				"show": {
					"operation": [
						"image"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "prompt"
				}
			}
		},
		{
			"displayName": "Style",
			"name": "image_style",
			"description": "Style notes, e.g. \"editorial photography, warm light\".",
			"displayOptions": {
				"show": {
					"operation": [
						"image"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "style",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Aspect Ratio",
			"name": "image_aspectRatio",
			"displayOptions": {
				"show": {
					"operation": [
						"image"
					]
				}
			},
			"type": "options",
			"options": [
				{
					"name": "1:1",
					"value": "1:1"
				},
				{
					"name": "16:9",
					"value": "16:9"
				},
				{
					"name": "9:16",
					"value": "9:16"
				},
				{
					"name": "4:3",
					"value": "4:3"
				},
				{
					"name": "3:4",
					"value": "3:4"
				}
			],
			"default": "1:1",
			"routing": {
				"send": {
					"type": "body",
					"property": "aspectRatio"
				}
			}
		},
		{
			"displayName": "Text",
			"name": "speak_text",
			"displayOptions": {
				"show": {
					"operation": [
						"speak"
					]
				}
			},
			"required": true,
			"type": "string",
			"default": "",
			"typeOptions": {
				"rows": 4
			},
			"routing": {
				"send": {
					"type": "body",
					"property": "text"
				}
			}
		},
		{
			"displayName": "Voice",
			"name": "speak_voice",
			"description": "Voice name; omit for the default narrator.",
			"displayOptions": {
				"show": {
					"operation": [
						"speak"
					]
				}
			},
			"type": "string",
			"default": "",
			"routing": {
				"send": {
					"type": "body",
					"property": "voice",
					"value": "={{ $value || undefined }}"
				}
			}
		},
		{
			"displayName": "Pace",
			"name": "speak_pace",
			"displayOptions": {
				"show": {
					"operation": [
						"speak"
					]
				}
			},
			"type": "options",
			"options": [
				{
					"name": "Slow",
					"value": "slow"
				},
				{
					"name": "Normal",
					"value": "normal"
				},
				{
					"name": "Fast",
					"value": "fast"
				}
			],
			"default": "normal",
			"routing": {
				"send": {
					"type": "body",
					"property": "pace"
				}
			}
		}
	]
} as unknown as Omit<INodeTypeDescription, 'inputs' | 'outputs'>),
	inputs: ['main' as NodeConnectionType],
	outputs: ['main' as NodeConnectionType],
} satisfies INodeTypeDescription;
